### ISSUE TITLE
Populate ORM with "betänkanden"

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#17]

**Comment by joelgoop** [comment]
First attempt in 7d5b4811e9b2913e70f0bfd9f4e23ca106fd6d3d.

**Comment by jeinarsson** [comment]
Right, since "utskottsforslag" ("punkter") will take some time to get to I propose that @joelgoop 

1) Adds a new subclass to Group which represents an "utskott" (Committee?)
2) Makes a relation from Poll to Committee, which indicates the Committee that prepared the Betänkande for the Poll
3) Populates said tables and relations in populate_orm.py, which should not require reading any additional data from riksdagen.se at the moment.

**Comment by joelgoop** [comment]
Functionality like above in place since 3a3b77606acaae9479d527f5b5c9762e24a27987 with some minor adjustments. The 'utskottsforslag' are in the ORM structure as `PolledPoint` and the `Poll` class has been removed. `PolledPoint` contains a `report` which is a `CommitteeReport` which is connected to a `Committee`. 

As far as I have been able to test it, everything works fine.
