### ISSUE TITLE
Vagrant VM dev environment config

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#2]
Perhaps for a rainy day: automagic consistent dev environments
https://danielgroves.net/notebook/2014/05/development-environments/
http://hakunin.com/six-ansible-practices

**Comment by joelgoop** [comment]
Vagrant seems like a [nice idea](http://mitchellh.com/the-tao-of-vagrant). I don't really understand Ansible yet, but as far as I can tell it doesn't run on Windows.

If we are to set up a common development environment a good, fairly simple first step is probably to run Vagrant with a `shell` provisioner, basically performing the steps in [the readme](../README.md). Most people seem to be using Vagrant to run a web app in the VM which they can then access from the outside, but in principle I guess you can just run Python scripts directly in Vagrant.

There also seem to be some more sofisticated ways of running Vagrant. For example, you can combine it with [Docker](https://docker.com/). Didn't you mention Docker, @joharohl? Any input on this approach? There are existing Docker images with e.g. Postgres and also Python environments. Does seem a little bit messy to set up though (but really nice when a working dev environment can be initialized directly after clone with only `vagrant up`).

**Comment by joharohl** [comment]
I also thinks it looks like a nice idea. Ansible doesn't seem very complicated, it is basically a way to organize tasks to setup the dev environment in a good way, but as you say Windows support seems to be a bit lacking. There seems to be ways around it though. 

I wouldn't mind looking into it, I kind of enjoy the sysadmin work. 

PS. I think docker would overcomplicate things on the development side. Since it is a more lightweight way to run multiple "apps" on one machine I think it is more suited on the deployment side where resources are more expensive. For local development, running several VMs shouldn't be that much of a problem and you can still get `vagrant up` to completely setup the environment.

**Comment by joelgoop** [comment]
That would be great!

**Comment by jeinarsson** [comment]
My vision of how it would work for me (I'm on Windows):
I start a VirtualBox which runs the servers and the app (python i bash is fine for the "hacking"). Then there's a shared folder with the code which I hack in with my usual Windows workflow.

Probably I could have everything in the vm (sublime text, git, ...) and just run it fullscreen, I guess. But "vagrant up" to have the db and all python dependencies would be ../ >_< ../

**Comment by joharohl** [comment]
There is a working branch for unix right now. The problem for windows is that Ansible is unix only. There seems to be a way to run ansible inside the Vm though. Looking into that.

**Comment by joharohl** [comment]
The branch works for both unix and windows now. Have a go :)

**Comment by joharohl** [comment]
or merge them. I don't dare.
