### ISSUE TITLE
Import field "riksmöte"

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#27]
where appropriate, perhaps in Poll and the documents later

**Comment by joelgoop** [comment]
I have included it for documents in the ongoing effort to import betänkanden (I chose to call it session, since that seems to be the closest translation). It would be easy to include it in polls as well, but a question I have is whether the 'riksmöte' of a document and a poll (regarding a document) can be different? Or does it have to be voted on during the same 'riksmöte' as when it's submitted?

**Comment by jeinarsson** [comment]
> does it have to be voted on during the same 'riksmöte' as when it's submitted?

I think so, or at least we could approximate it so for now.

Also I realised that the "Poll" class is not needed now that you have PolledCommitteReport (or whatever it was), because votes could be tied directly to the PolledCommitteReport without loss of generality. (that is, merge Poll and PolledCommitteReport if you agree)
