### ISSUE TITLE
Is there a reason run.py was removed?

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#32]
I have used `run.py` to run the web app, since it shows nice tracebacks when there are errors (with `gunicorn_debug` you only get "Internal Server Error"). It was removed some time ago, so I'm wondering if there was a particular reason? I put it back in 3e8f5cf8. If that's fine, feel free to close this issue.

**Comment by joharohl** [comment]
The main reason for not using run.py is that it uses the werkzeug webserver which is not recommended in production. I think that trying to keep as close to the production environment during development reduces the risks for bugs. I used the cmd-line stack traces from gunicorn but I realise that I would panic less if I used the werkzeug one. So in this case I agree that it is better to run in werkzeug. I added a bash alias `werkzeug_debug` for running run.py so that both options exist. A `vagrant provision` should get it into `.bashrc`. 

The probability is low but it might be a good idea to try the app in gunicorn every now and then just to see if something works differently. 

Finally, I removed the debug flag from config.py since it is specified within `run.py` and should help with running the app in production using gunicorn later later on.
