### ISSUE TITLE
Chairs figure

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#34]
How about making a nice figure over the current seats in the riksdag?

Something like one of these:
http://gfx.aftonbladet-cdn.se/image/19536930/800/normal/f223fd53c9df4/mobil.gif
http://upload.wikimedia.org/wikipedia/commons/1/14/2010_Riksdag_Structure.png

but interactive of course.

**Comment by rasmuse** [comment]
Yes please!

**Comment by jeinarsson** [comment]
Yes indeed!

I lean towards the more schematic version if grouped by party, since the actual seating is different in the chamber. 

But perhaps the actual seating by 'valdistrikt' is also interesting? I can't find a map of the chair numbers though. You could write to them ;)

Perhaps different 'modes', like heatmaps for voting attendance, number of 'motioner', 'interpellationer' etc?

Mouseover popups? Or fisheye mode http://bost.ocks.org/mike/fisheye/ ? Just throwing ideas, don't mind if they don't stick

**Comment by joharohl** [comment]
Check it out :D

**Comment by joharohl** [comment]
It is sorted on chair right now so not very easy to get a hang of the proportions. Added "links" between the circles and the members for now, just to demonstrate that controlling each dot works. Surprisingly few lines of code to produce it. But getting it exactly they way we want might be a whole other story. Oh, and the url is /members/riksdagen.html

**Comment by jeinarsson** [comment]
Fantastic! (Except my machine took hours to vagrant and import data ;)

If each circle object is identified with a member, and a member with a
position, you could have buttons for re-sorting the members according to
physical position in chamber or by some abstract party-wise sorting, and d3
would make some sweet transition in between.

Modern JS is confusing me greatly also, but I'll get used to it..

Keep playing with this figure. It's our first "real" d3 vis. :)

**Comment by joharohl** [comment]
Closed by df90f076d0cd595757e43478baa1571fb1a4ef2b
