### ISSUE TITLE
Initial deployment

### ISSUE THREAD

**Issue by jeinarsson** [demokratikollen/demokratikollen#36]
Notes after epic-lunch-meeting-with-surprise-cake:
@joharohl will

1) Get $10 cloud account,
2) Do some Docker magic such that
 a) a (tag in a) new branch 'deploy' is running and accessible on some URL
 b) there are in principle two deployed apps: "Cold" and "Hot", where Hot is the one online. Every night (or so) the Cold version is updated with new data and tests are run. If tests pass, Hot and Cold switch places.

When we have a somewhat persistent PostgreSQL instance we should think about how to (more) incrementally update the Riksdagen database. If we continue downloading everything from data.riksdagen we will eventually be IP-banned .. :)

**Comment by joharohl** [comment]
1. Done

All pushes to any branch will result in wercker trying to build them. Right now, nothing is done except installing requirements. Once tests are implemented it should be trivial to run them as part of the build process. 

Any successful build of the deploy branch will automatically copy the app to the Digital Ocean server. One small step at a time.

**Comment by jeinarsson** [comment]
Is it live!? Or just copied? What does "build " mean?

**Comment by jeinarsson** [comment]
I'm following every commit inbetween putting Freja to bed ;)

**Comment by joharohl** [comment]
It's finally done in 9bfaf05a01363a75fdc2c141af119d0e6430a425. Its ugly hacky as hell but it works. Any push to deploy will now be auto-deployed to a digital ocean vps. In principal, the source is copied to the vps from wercker and then a shell script is executed via ssh. The script removes the docker images and rebuilds them according to the Dockerfiles present in `dockerfiles` and some additional steps in `deployment.sh`. It takes around 13 minutes to do a full rebuild so not that bad. Will continue working on a more sophisticated system but there is a lot to learn.

I had to change a bit to get everything working reasonably. Some where just the move from Poll -> PolledPoint but in order to not download all the sqls every time I had to hack away in data_import as well. Someone that feel ready for the task of merging this with develop can have a go :)

Anyhow, it is online for the first time at http://146.185.188.12   check it out.

**Comment by jeinarsson** [comment]
Holy crap. This rocks my socks. Were onto a 1.0 release, let's finish a
roadmap there!

Tomorrow we'll celebrate with lamb roast and sauna. Sauna 19-21. Food
before that. Hack and hangout before that, starting lunch-time. Tell me if
you bring too much company, you might need to help the chef ;)

J
