### ISSUE TITLE
Installation of ruby gems not working

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#61]
I am trying to install webdev stuff from scratch by running `vagrant provision` (or `up`), but `compass install` fails:

```
==> default: TASK: [webdev | Install bootstrap into Compass project] ***********
************
==> default: failed: [localhost] => {"cmd": "compass ******** bootstrap -c /home
/vagrant/demokratikollen/demokratikollen-compass******** --app-dir /home/vagrant
/demokratikollen/demokratikollen-compass********", "failed": true, "rc": 2}
==> default: msg: [Errno 2] No such file or directory
==> default:
==> default: FATAL: all hosts have already failed -- aborting
```

When I log in via `ssh`, the `compass` command is not available even though the installation of Compass has succeeded according to ansible:

```
==> default: TASK: [webdev | Install some Ruby gems] ***************************
************
==> default: ok: [localhost] => (item=bootstrap-sass)
==> default: ok: [localhost] => (item=compass)
==> default: ok: [localhost] => (item=bundler)
```

If I run `sudo gem install compass`, it successfully installs Compass and makes the command available.

**Comment by joharohl** [comment]
The issue is with the `gem` plugin for ansible. As default it installs gems per user and since you are using sudo it installs it as root. For some reason, subsequent calls with sudo still don't find the gems. Perhaps it has something to do with bash_rc stuff. 

Anyway, the solution is to run `sudo rm -rf /root/.gem` on the VM first (otherwise Ansible believe they are installed) followed by adding `user_install=no` to the gem command in the Ansible role.

I didn't want to push this since you are working with it right now so go ahead and try it. 

PS. I got some more errors concerning present directories. I figure you know what to do with them.

**Comment by rasmuse** [comment]
@joharohl: `sudo rm -rf /root/.gem` on the virtual machine, right?

**Comment by joharohl** [comment]
yes. that was a typo.

**Comment by rasmuse** [comment]
You are excused.

**Comment by joelgoop** [comment]
I have tried the fix and it works. I have committed and pushed in 6f4f380ecc8d1b91a4741565656fcd5df8fccc89. I also had to add `ignore_errors: True` to the compass install task, otherwise the provisioning will fail when files already exists (it writes to `stderr` which ansible notes as fail). This is not a good fix, but it will do for now. If you know of a better way, please change it!
