### ISSUE TITLE
Suggestion for app structure

### ISSUE THREAD

**Issue by joharohl** [demokratikollen/demokratikollen#67]

**Comment by joharohl** [comment]
I just made a new branch to do the generation of gender stats data. In the process I restructured the app yet again. Just wanted to check with you if you think that the current one is the one to use. (check the 66-gender-plot-json  branch for the code)

I read some more and this is what I come up with: 

Routes are still defined in blueprints that are sectioned in some logical way (I am not sure how yet).  No app logic is contained in these routing files. Instead, the logic is contained in controllers located in the controllers dir. The routers only call the correct controller method and passes on user data. I think this way should keep the code nicely separated and model-like behaviour can be kept in the controllers, or even separated out into models, without exposing it to the routing, easing reuse and extensions.

So, what do you think?

**Comment by jeinarsson** [comment]
Much better, the controllers tended to get long and messy.

J

**Comment by joelgoop** [comment]
I agree. It sounds like a great idea to separate routes and logic.

But just to make sure I get it: The modules (`mod_members` etc) are going away and instead we have a routes folder and a controllers folder?

**Comment by jeinarsson** [comment]
When you're happy with the _structure_, merge this to develop (and close this issue) so I can start adding "my" data there aswell :)

**Comment by joharohl** [comment]
Its merged. Naming of the different stuff is still open for changes but I presume it will be settled down the road.

**Comment by rasmuse** [comment]
After working a bit with the new proposed structure and looking at some Flask use cases, I wanted to restructure the `www/app` code once again. Please see branch `bootstrap-template` at commit 571d850e4dc59a89ac95439b0daedaa5e6e5836c for current status.

Before explaining why and how: I read up a little bit on Flask and learned that there is no such thing as "controller", but only "view function" (\approx "controller" in MVC terminology) and "template" (\approx "view"). So now I'll write "view" or "view function" below, in accordance with Flask terminology.

A problem with separating routes from view functions, as @joharohl proposed, is that it tends to create a lot of repetitions in the code: A routing functions unpacks arguments, and the corresponding view function then typically uses a very similar list of arguments. If you change something in the list of arguments for a page, it will almost always have to be changed in two places with the current structure. Also, we don't want view functions to be too long and complicated as @joharohl noted. So my analysis/suggestion for improved DRYness follows:
1. We should not keep complicated and potentially reusable logic in view functions, because it will tend to make view functions very long and to hinder code reuse. Instead, we put all potentially reusable parts of the "business logic" in a separate place, which I just named `models`. The structure of `models` is not very important. Let's just start building it and refactor as we go along.
2. Routing and view functions are tightly coupled things. Let's keep them together pretty much like we did first: We decorate view functions with `@route` decorators, and we keep them all in a folder called `views`. For now, I have two blueprints (`data` and `pages`), that I put in two separate files (`views/data.py` and `views/pages.py`). View functions should not contain a lot of complicated logic. Typically, a view function should mostly 1) get the arguments that come with the request, 2) use those arguments to fetch some data from `models.something()`, and 3) render a template with the data.

Please have a look at the current status 571d850e4dc59a89ac95439b0daedaa5e6e5836c and let me know if you think we should merge it to `develop`.

**Comment by joharohl** [comment]
I think it sounds like a good idea. I am too stuck in a pure MVC framework I think. I started using the old structure and the code ended up pretty much as you describe it with the routes file taking care of a view functions work and the controller being a model. 

Merge it in. I have to refactor some stuff but it shouldn't be that hard.

**Comment by jeinarsson** [comment]
I merged it to develop (I did not remove the bootstrap branch, I'll leave that to the owner..)

The behave tests pass, but the nosetests do not. If I run 
nosetests specs it runs 0 tests (OK)

If I run only 
nosetests
it runs the tests in app_old and fails? I don't get it, but probably @joharohl knows what do do about it. When the unittests run we'll have bootstrap fancypants on the vps yay!

**Comment by joharohl** [comment]
I fixed the testing stuff when dealing with the gender fig. I can merge
that to develop as well. It adheres to the new app format so should be easy
to merge.
Den 22 nov 2014 22:42 skrev "Jonas Einarsson" notifications@github.com:

**Comment by joharohl** [comment]
I believe the new structure is settled, so closing. Some renaming of models will surely happen but that is not related to this issue.
