### ISSUE TITLE
Sankey diagram of 'motioner' and 'propositioner'

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#72]
Visualize flow of proposals from parties/government to committees to approval/refusal in the chamber with the [D3 Sankey plugin](http://bost.ocks.org/mike/sankey/). An overwhelming majority of all member proposals ('motioner') gets refused by the chamber, but maybe the flow from parties to committees can be interesting anyway.

Requires #46 and #24.

**Comment by rasmuse** [comment]
I did some alpha testing with our friends P&S yesterday. Feedback on the sankey diagram:
- General feedback: Looks great. Testers were impressed and found the figure informative although slightly complicated.
- Headlines on the top, above each "column" would be helpful, e.g. "Förslag från", "Utskott", "Beslut" or something like that.
- The figure is sometimes hard to read, mostly because of low contrast.
  - Tester P (who has impaired vision) could almost not distinguish e.g. yellow (sd) or green (mp) flows at all. Grey flows, e.g. from "Alla departement" worked better. 
  - Tester S (who has good vision), on the other hand, thought the contrast between dark grey (marked) flows and light grey flows (background) was too weak. Colored flows, even the bright yellow one, were easier to distinguish.
- Label "Alla departement" is confusing. Testers proposed instead: "Regeringen".
- Zooming in the figure works great.
- A little bit slow on iPad (version unknown) with Safari (version unknown), but testers did not find it very annoying.

**Comment by jeinarsson** [comment]
https://github.com/joelgoop/demokratikollen/commit/0bc0f52da2739952587d78173563ba386562f290
