### ISSUE TITLE
The download of search data is slow

### ISSUE THREAD

**Issue by joelgoop** [demokratikollen/demokratikollen#94]
The request for search data takes around 15-60 s on my computer and connection (Chalmers). Is this a new problem or was our VPS always this slow? Maybe we should divide the data to load current members first and the rest later or something?

A side note: Shouldn't the `search.json` file be automatically cached locally? It doesn't seem to be for me (it is re-requested every time I load any page). What could be the reason?

**Comment by joharohl** [comment]
the search data loads really fast for me (< 1s). Which client? Could it be related to the with the recently cut fiber at sunet? 

Anyhow. The request is not cached which it of course should be. I can fix that.

**Comment by joharohl** [comment]
Fixed by adding default +1 day Expires header to all requests. The default expire can be overridden using the `@http_expires(seconds)` decorator on a view function. 

It is up to the clients to not get a new version of the file. This means that the expire should not be too far into the future unless there is a very small chance that the resource will change. 

A better way would be to use E-tag header which can be used to invalidate cached versions. I might look into this at a later point, but for now each session should at least be more snappy.
